// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: internal/proto/can/can.proto

package can

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common filter parameters
type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	CanId         *uint32                `protobuf:"varint,3,opt,name=can_id,json=canId,proto3,oneof" json:"can_id,omitempty"`
	Interface     string                 `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_internal_proto_can_can_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{0}
}

func (x *QueryFilter) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryFilter) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryFilter) GetCanId() uint32 {
	if x != nil && x.CanId != nil {
		return *x.CanId
	}
	return 0
}

func (x *QueryFilter) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *QueryFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// CAN Message
type CANMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	CanId         uint32                 `protobuf:"varint,3,opt,name=can_id,json=canId,proto3" json:"can_id,omitempty"`
	CanIdHex      string                 `protobuf:"bytes,4,opt,name=can_id_hex,json=canIdHex,proto3" json:"can_id_hex,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CANMessage) Reset() {
	*x = CANMessage{}
	mi := &file_internal_proto_can_can_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CANMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CANMessage) ProtoMessage() {}

func (x *CANMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CANMessage.ProtoReflect.Descriptor instead.
func (*CANMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{1}
}

func (x *CANMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CANMessage) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *CANMessage) GetCanId() uint32 {
	if x != nil {
		return x.CanId
	}
	return 0
}

func (x *CANMessage) GetCanIdHex() string {
	if x != nil {
		return x.CanIdHex
	}
	return ""
}

func (x *CANMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetMessages request/response
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_internal_proto_can_can_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*CANMessage          `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_internal_proto_can_can_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesResponse) GetMessages() []*CANMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// GetMessageCount request/response
type GetMessageCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageCountRequest) Reset() {
	*x = GetMessageCountRequest{}
	mi := &file_internal_proto_can_can_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageCountRequest) ProtoMessage() {}

func (x *GetMessageCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageCountRequest.ProtoReflect.Descriptor instead.
func (*GetMessageCountRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessageCountRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetMessageCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageCountResponse) Reset() {
	*x = GetMessageCountResponse{}
	mi := &file_internal_proto_can_can_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageCountResponse) ProtoMessage() {}

func (x *GetMessageCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageCountResponse.ProtoReflect.Descriptor instead.
func (*GetMessageCountResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageCountResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetUniqueCANIDs request/response
type GetUniqueCANIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniqueCANIDsRequest) Reset() {
	*x = GetUniqueCANIDsRequest{}
	mi := &file_internal_proto_can_can_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniqueCANIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniqueCANIDsRequest) ProtoMessage() {}

func (x *GetUniqueCANIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniqueCANIDsRequest.ProtoReflect.Descriptor instead.
func (*GetUniqueCANIDsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{6}
}

func (x *GetUniqueCANIDsRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type CANIDInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanId         uint32                 `protobuf:"varint,1,opt,name=can_id,json=canId,proto3" json:"can_id,omitempty"`
	CanIdHex      string                 `protobuf:"bytes,2,opt,name=can_id_hex,json=canIdHex,proto3" json:"can_id_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CANIDInfo) Reset() {
	*x = CANIDInfo{}
	mi := &file_internal_proto_can_can_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CANIDInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CANIDInfo) ProtoMessage() {}

func (x *CANIDInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CANIDInfo.ProtoReflect.Descriptor instead.
func (*CANIDInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{7}
}

func (x *CANIDInfo) GetCanId() uint32 {
	if x != nil {
		return x.CanId
	}
	return 0
}

func (x *CANIDInfo) GetCanIdHex() string {
	if x != nil {
		return x.CanIdHex
	}
	return ""
}

type GetUniqueCANIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanIds        []*CANIDInfo           `protobuf:"bytes,1,rep,name=can_ids,json=canIds,proto3" json:"can_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniqueCANIDsResponse) Reset() {
	*x = GetUniqueCANIDsResponse{}
	mi := &file_internal_proto_can_can_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniqueCANIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniqueCANIDsResponse) ProtoMessage() {}

func (x *GetUniqueCANIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniqueCANIDsResponse.ProtoReflect.Descriptor instead.
func (*GetUniqueCANIDsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{8}
}

func (x *GetUniqueCANIDsResponse) GetCanIds() []*CANIDInfo {
	if x != nil {
		return x.CanIds
	}
	return nil
}

// GetStatsByCANID request/response
type GetStatsByCANIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsByCANIDRequest) Reset() {
	*x = GetStatsByCANIDRequest{}
	mi := &file_internal_proto_can_can_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsByCANIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsByCANIDRequest) ProtoMessage() {}

func (x *GetStatsByCANIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsByCANIDRequest.ProtoReflect.Descriptor instead.
func (*GetStatsByCANIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatsByCANIDRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type CANIDStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanId         uint32                 `protobuf:"varint,1,opt,name=can_id,json=canId,proto3" json:"can_id,omitempty"`
	CanIdHex      string                 `protobuf:"bytes,2,opt,name=can_id_hex,json=canIdHex,proto3" json:"can_id_hex,omitempty"`
	MessageCount  uint64                 `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CANIDStats) Reset() {
	*x = CANIDStats{}
	mi := &file_internal_proto_can_can_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CANIDStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CANIDStats) ProtoMessage() {}

func (x *CANIDStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CANIDStats.ProtoReflect.Descriptor instead.
func (*CANIDStats) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{10}
}

func (x *CANIDStats) GetCanId() uint32 {
	if x != nil {
		return x.CanId
	}
	return 0
}

func (x *CANIDStats) GetCanIdHex() string {
	if x != nil {
		return x.CanIdHex
	}
	return ""
}

func (x *CANIDStats) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *CANIDStats) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *CANIDStats) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type GetStatsByCANIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*CANIDStats          `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsByCANIDResponse) Reset() {
	*x = GetStatsByCANIDResponse{}
	mi := &file_internal_proto_can_can_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsByCANIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsByCANIDResponse) ProtoMessage() {}

func (x *GetStatsByCANIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsByCANIDResponse.ProtoReflect.Descriptor instead.
func (*GetStatsByCANIDResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatsByCANIDResponse) GetStats() []*CANIDStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// GetCANopenMessages request/response
type GetCANopenMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // nmt, sync, emcy, pdo, sdo, heartbeat
	NodeId        *uint32                `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"`
	PdoMappings   map[string]string      `protobuf:"bytes,4,rep,name=pdo_mappings,json=pdoMappings,proto3" json:"pdo_mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key: tpdo1/rpdo1, value: field mapping string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCANopenMessagesRequest) Reset() {
	*x = GetCANopenMessagesRequest{}
	mi := &file_internal_proto_can_can_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCANopenMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCANopenMessagesRequest) ProtoMessage() {}

func (x *GetCANopenMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCANopenMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetCANopenMessagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{12}
}

func (x *GetCANopenMessagesRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetCANopenMessagesRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *GetCANopenMessagesRequest) GetNodeId() uint32 {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return 0
}

func (x *GetCANopenMessagesRequest) GetPdoMappings() map[string]string {
	if x != nil {
		return x.PdoMappings
	}
	return nil
}

type CANopenMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	CanId         uint32                 `protobuf:"varint,3,opt,name=can_id,json=canId,proto3" json:"can_id,omitempty"`
	CanIdHex      string                 `protobuf:"bytes,4,opt,name=can_id_hex,json=canIdHex,proto3" json:"can_id_hex,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	MessageType   string                 `protobuf:"bytes,6,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	NodeId        uint32                 `protobuf:"varint,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ParsedData    map[string]string      `protobuf:"bytes,8,rep,name=parsed_data,json=parsedData,proto3" json:"parsed_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // parsed PDO data if available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CANopenMessage) Reset() {
	*x = CANopenMessage{}
	mi := &file_internal_proto_can_can_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CANopenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CANopenMessage) ProtoMessage() {}

func (x *CANopenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CANopenMessage.ProtoReflect.Descriptor instead.
func (*CANopenMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{13}
}

func (x *CANopenMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CANopenMessage) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *CANopenMessage) GetCanId() uint32 {
	if x != nil {
		return x.CanId
	}
	return 0
}

func (x *CANopenMessage) GetCanIdHex() string {
	if x != nil {
		return x.CanIdHex
	}
	return ""
}

func (x *CANopenMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CANopenMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *CANopenMessage) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *CANopenMessage) GetParsedData() map[string]string {
	if x != nil {
		return x.ParsedData
	}
	return nil
}

type GetCANopenMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*CANopenMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCANopenMessagesResponse) Reset() {
	*x = GetCANopenMessagesResponse{}
	mi := &file_internal_proto_can_can_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCANopenMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCANopenMessagesResponse) ProtoMessage() {}

func (x *GetCANopenMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCANopenMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetCANopenMessagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{14}
}

func (x *GetCANopenMessagesResponse) GetMessages() []*CANopenMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// GetCANopenStats request/response
type GetCANopenStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCANopenStatsRequest) Reset() {
	*x = GetCANopenStatsRequest{}
	mi := &file_internal_proto_can_can_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCANopenStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCANopenStatsRequest) ProtoMessage() {}

func (x *GetCANopenStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCANopenStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCANopenStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{15}
}

func (x *GetCANopenStatsRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type CANopenMessageTypeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	MessageCount  uint64                 `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CANopenMessageTypeStats) Reset() {
	*x = CANopenMessageTypeStats{}
	mi := &file_internal_proto_can_can_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CANopenMessageTypeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CANopenMessageTypeStats) ProtoMessage() {}

func (x *CANopenMessageTypeStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CANopenMessageTypeStats.ProtoReflect.Descriptor instead.
func (*CANopenMessageTypeStats) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{16}
}

func (x *CANopenMessageTypeStats) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *CANopenMessageTypeStats) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *CANopenMessageTypeStats) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *CANopenMessageTypeStats) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type GetCANopenStatsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Stats         []*CANopenMessageTypeStats `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCANopenStatsResponse) Reset() {
	*x = GetCANopenStatsResponse{}
	mi := &file_internal_proto_can_can_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCANopenStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCANopenStatsResponse) ProtoMessage() {}

func (x *GetCANopenStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_can_can_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCANopenStatsResponse.ProtoReflect.Descriptor instead.
func (*GetCANopenStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_can_can_proto_rawDescGZIP(), []int{17}
}

func (x *GetCANopenStatsResponse) GetStats() []*CANopenMessageTypeStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_internal_proto_can_can_proto protoreflect.FileDescriptor

const file_internal_proto_can_can_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/can/can.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\vQueryFilter\x12>\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartTime\x88\x01\x01\x12:\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendTime\x88\x01\x01\x12\x1a\n" +
	"\x06can_id\x18\x03 \x01(\rH\x02R\x05canId\x88\x01\x01\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offsetB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_timeB\t\n" +
	"\a_can_id\"\xad\x01\n" +
	"\n" +
	"CANMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x15\n" +
	"\x06can_id\x18\x03 \x01(\rR\x05canId\x12\x1c\n" +
	"\n" +
	"can_id_hex\x18\x04 \x01(\tR\bcanIdHex\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"@\n" +
	"\x12GetMessagesRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.proto.QueryFilterR\x06filter\"D\n" +
	"\x13GetMessagesResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.proto.CANMessageR\bmessages\"D\n" +
	"\x16GetMessageCountRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.proto.QueryFilterR\x06filter\"/\n" +
	"\x17GetMessageCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"D\n" +
	"\x16GetUniqueCANIDsRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.proto.QueryFilterR\x06filter\"@\n" +
	"\tCANIDInfo\x12\x15\n" +
	"\x06can_id\x18\x01 \x01(\rR\x05canId\x12\x1c\n" +
	"\n" +
	"can_id_hex\x18\x02 \x01(\tR\bcanIdHex\"D\n" +
	"\x17GetUniqueCANIDsResponse\x12)\n" +
	"\acan_ids\x18\x01 \x03(\v2\x10.proto.CANIDInfoR\x06canIds\"D\n" +
	"\x16GetStatsByCANIDRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.proto.QueryFilterR\x06filter\"\xda\x01\n" +
	"\n" +
	"CANIDStats\x12\x15\n" +
	"\x06can_id\x18\x01 \x01(\rR\x05canId\x12\x1c\n" +
	"\n" +
	"can_id_hex\x18\x02 \x01(\tR\bcanIdHex\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x04R\fmessageCount\x129\n" +
	"\n" +
	"first_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"B\n" +
	"\x17GetStatsByCANIDResponse\x12'\n" +
	"\x05stats\x18\x01 \x03(\v2\x11.proto.CANIDStatsR\x05stats\"\xaa\x02\n" +
	"\x19GetCANopenMessagesRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.proto.QueryFilterR\x06filter\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12\x1c\n" +
	"\anode_id\x18\x03 \x01(\rH\x00R\x06nodeId\x88\x01\x01\x12T\n" +
	"\fpdo_mappings\x18\x04 \x03(\v21.proto.GetCANopenMessagesRequest.PdoMappingsEntryR\vpdoMappings\x1a>\n" +
	"\x10PdoMappingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_node_id\"\xf4\x02\n" +
	"\x0eCANopenMessage\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x15\n" +
	"\x06can_id\x18\x03 \x01(\rR\x05canId\x12\x1c\n" +
	"\n" +
	"can_id_hex\x18\x04 \x01(\tR\bcanIdHex\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12!\n" +
	"\fmessage_type\x18\x06 \x01(\tR\vmessageType\x12\x17\n" +
	"\anode_id\x18\a \x01(\rR\x06nodeId\x12F\n" +
	"\vparsed_data\x18\b \x03(\v2%.proto.CANopenMessage.ParsedDataEntryR\n" +
	"parsedData\x1a=\n" +
	"\x0fParsedDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x1aGetCANopenMessagesResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.proto.CANopenMessageR\bmessages\"D\n" +
	"\x16GetCANopenStatsRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.proto.QueryFilterR\x06filter\"\xd5\x01\n" +
	"\x17CANopenMessageTypeStats\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x04R\fmessageCount\x129\n" +
	"\n" +
	"first_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"O\n" +
	"\x17GetCANopenStatsResponse\x124\n" +
	"\x05stats\x18\x01 \x03(\v2\x1e.proto.CANopenMessageTypeStatsR\x05stats2\xf5\x03\n" +
	"\n" +
	"canService\x12D\n" +
	"\vGetMessages\x12\x19.proto.GetMessagesRequest\x1a\x1a.proto.GetMessagesResponse\x12P\n" +
	"\x0fGetMessageCount\x12\x1d.proto.GetMessageCountRequest\x1a\x1e.proto.GetMessageCountResponse\x12P\n" +
	"\x0fGetUniqueCANIDs\x12\x1d.proto.GetUniqueCANIDsRequest\x1a\x1e.proto.GetUniqueCANIDsResponse\x12P\n" +
	"\x0fGetStatsByCANID\x12\x1d.proto.GetStatsByCANIDRequest\x1a\x1e.proto.GetStatsByCANIDResponse\x12Y\n" +
	"\x12GetCANopenMessages\x12 .proto.GetCANopenMessagesRequest\x1a!.proto.GetCANopenMessagesResponse\x12P\n" +
	"\x0fGetCANopenStats\x12\x1d.proto.GetCANopenStatsRequest\x1a\x1e.proto.GetCANopenStatsResponseB\"Z can-db-writer/internal/proto/canb\x06proto3"

var (
	file_internal_proto_can_can_proto_rawDescOnce sync.Once
	file_internal_proto_can_can_proto_rawDescData []byte
)

func file_internal_proto_can_can_proto_rawDescGZIP() []byte {
	file_internal_proto_can_can_proto_rawDescOnce.Do(func() {
		file_internal_proto_can_can_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_can_can_proto_rawDesc), len(file_internal_proto_can_can_proto_rawDesc)))
	})
	return file_internal_proto_can_can_proto_rawDescData
}

var file_internal_proto_can_can_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_proto_can_can_proto_goTypes = []any{
	(*QueryFilter)(nil),                // 0: proto.QueryFilter
	(*CANMessage)(nil),                 // 1: proto.CANMessage
	(*GetMessagesRequest)(nil),         // 2: proto.GetMessagesRequest
	(*GetMessagesResponse)(nil),        // 3: proto.GetMessagesResponse
	(*GetMessageCountRequest)(nil),     // 4: proto.GetMessageCountRequest
	(*GetMessageCountResponse)(nil),    // 5: proto.GetMessageCountResponse
	(*GetUniqueCANIDsRequest)(nil),     // 6: proto.GetUniqueCANIDsRequest
	(*CANIDInfo)(nil),                  // 7: proto.CANIDInfo
	(*GetUniqueCANIDsResponse)(nil),    // 8: proto.GetUniqueCANIDsResponse
	(*GetStatsByCANIDRequest)(nil),     // 9: proto.GetStatsByCANIDRequest
	(*CANIDStats)(nil),                 // 10: proto.CANIDStats
	(*GetStatsByCANIDResponse)(nil),    // 11: proto.GetStatsByCANIDResponse
	(*GetCANopenMessagesRequest)(nil),  // 12: proto.GetCANopenMessagesRequest
	(*CANopenMessage)(nil),             // 13: proto.CANopenMessage
	(*GetCANopenMessagesResponse)(nil), // 14: proto.GetCANopenMessagesResponse
	(*GetCANopenStatsRequest)(nil),     // 15: proto.GetCANopenStatsRequest
	(*CANopenMessageTypeStats)(nil),    // 16: proto.CANopenMessageTypeStats
	(*GetCANopenStatsResponse)(nil),    // 17: proto.GetCANopenStatsResponse
	nil,                                // 18: proto.GetCANopenMessagesRequest.PdoMappingsEntry
	nil,                                // 19: proto.CANopenMessage.ParsedDataEntry
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
}
var file_internal_proto_can_can_proto_depIdxs = []int32{
	20, // 0: proto.QueryFilter.start_time:type_name -> google.protobuf.Timestamp
	20, // 1: proto.QueryFilter.end_time:type_name -> google.protobuf.Timestamp
	20, // 2: proto.CANMessage.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: proto.GetMessagesRequest.filter:type_name -> proto.QueryFilter
	1,  // 4: proto.GetMessagesResponse.messages:type_name -> proto.CANMessage
	0,  // 5: proto.GetMessageCountRequest.filter:type_name -> proto.QueryFilter
	0,  // 6: proto.GetUniqueCANIDsRequest.filter:type_name -> proto.QueryFilter
	7,  // 7: proto.GetUniqueCANIDsResponse.can_ids:type_name -> proto.CANIDInfo
	0,  // 8: proto.GetStatsByCANIDRequest.filter:type_name -> proto.QueryFilter
	20, // 9: proto.CANIDStats.first_seen:type_name -> google.protobuf.Timestamp
	20, // 10: proto.CANIDStats.last_seen:type_name -> google.protobuf.Timestamp
	10, // 11: proto.GetStatsByCANIDResponse.stats:type_name -> proto.CANIDStats
	0,  // 12: proto.GetCANopenMessagesRequest.filter:type_name -> proto.QueryFilter
	18, // 13: proto.GetCANopenMessagesRequest.pdo_mappings:type_name -> proto.GetCANopenMessagesRequest.PdoMappingsEntry
	20, // 14: proto.CANopenMessage.timestamp:type_name -> google.protobuf.Timestamp
	19, // 15: proto.CANopenMessage.parsed_data:type_name -> proto.CANopenMessage.ParsedDataEntry
	13, // 16: proto.GetCANopenMessagesResponse.messages:type_name -> proto.CANopenMessage
	0,  // 17: proto.GetCANopenStatsRequest.filter:type_name -> proto.QueryFilter
	20, // 18: proto.CANopenMessageTypeStats.first_seen:type_name -> google.protobuf.Timestamp
	20, // 19: proto.CANopenMessageTypeStats.last_seen:type_name -> google.protobuf.Timestamp
	16, // 20: proto.GetCANopenStatsResponse.stats:type_name -> proto.CANopenMessageTypeStats
	2,  // 21: proto.canService.GetMessages:input_type -> proto.GetMessagesRequest
	4,  // 22: proto.canService.GetMessageCount:input_type -> proto.GetMessageCountRequest
	6,  // 23: proto.canService.GetUniqueCANIDs:input_type -> proto.GetUniqueCANIDsRequest
	9,  // 24: proto.canService.GetStatsByCANID:input_type -> proto.GetStatsByCANIDRequest
	12, // 25: proto.canService.GetCANopenMessages:input_type -> proto.GetCANopenMessagesRequest
	15, // 26: proto.canService.GetCANopenStats:input_type -> proto.GetCANopenStatsRequest
	3,  // 27: proto.canService.GetMessages:output_type -> proto.GetMessagesResponse
	5,  // 28: proto.canService.GetMessageCount:output_type -> proto.GetMessageCountResponse
	8,  // 29: proto.canService.GetUniqueCANIDs:output_type -> proto.GetUniqueCANIDsResponse
	11, // 30: proto.canService.GetStatsByCANID:output_type -> proto.GetStatsByCANIDResponse
	14, // 31: proto.canService.GetCANopenMessages:output_type -> proto.GetCANopenMessagesResponse
	17, // 32: proto.canService.GetCANopenStats:output_type -> proto.GetCANopenStatsResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_proto_can_can_proto_init() }
func file_internal_proto_can_can_proto_init() {
	if File_internal_proto_can_can_proto != nil {
		return
	}
	file_internal_proto_can_can_proto_msgTypes[0].OneofWrappers = []any{}
	file_internal_proto_can_can_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_can_can_proto_rawDesc), len(file_internal_proto_can_can_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_can_can_proto_goTypes,
		DependencyIndexes: file_internal_proto_can_can_proto_depIdxs,
		MessageInfos:      file_internal_proto_can_can_proto_msgTypes,
	}.Build()
	File_internal_proto_can_can_proto = out.File
	file_internal_proto_can_can_proto_goTypes = nil
	file_internal_proto_can_can_proto_depIdxs = nil
}
