// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: internal/proto/can/can.proto

package can

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CanService_GetMessages_FullMethodName        = "/proto.canService/GetMessages"
	CanService_GetMessageCount_FullMethodName    = "/proto.canService/GetMessageCount"
	CanService_GetUniqueCANIDs_FullMethodName    = "/proto.canService/GetUniqueCANIDs"
	CanService_GetStatsByCANID_FullMethodName    = "/proto.canService/GetStatsByCANID"
	CanService_GetCANopenMessages_FullMethodName = "/proto.canService/GetCANopenMessages"
	CanService_GetCANopenStats_FullMethodName    = "/proto.canService/GetCANopenStats"
)

// CanServiceClient is the client API for CanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CanServiceClient interface {
	// Get CAN messages with optional filters
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	// Get message count with optional filters
	GetMessageCount(ctx context.Context, in *GetMessageCountRequest, opts ...grpc.CallOption) (*GetMessageCountResponse, error)
	// Get unique CAN IDs
	GetUniqueCANIDs(ctx context.Context, in *GetUniqueCANIDsRequest, opts ...grpc.CallOption) (*GetUniqueCANIDsResponse, error)
	// Get statistics grouped by CAN ID
	GetStatsByCANID(ctx context.Context, in *GetStatsByCANIDRequest, opts ...grpc.CallOption) (*GetStatsByCANIDResponse, error)
	// Get CANopen messages classified by message type
	GetCANopenMessages(ctx context.Context, in *GetCANopenMessagesRequest, opts ...grpc.CallOption) (*GetCANopenMessagesResponse, error)
	// Get CANopen statistics grouped by message type
	GetCANopenStats(ctx context.Context, in *GetCANopenStatsRequest, opts ...grpc.CallOption) (*GetCANopenStatsResponse, error)
}

type canServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCanServiceClient(cc grpc.ClientConnInterface) CanServiceClient {
	return &canServiceClient{cc}
}

func (c *canServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, CanService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canServiceClient) GetMessageCount(ctx context.Context, in *GetMessageCountRequest, opts ...grpc.CallOption) (*GetMessageCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageCountResponse)
	err := c.cc.Invoke(ctx, CanService_GetMessageCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canServiceClient) GetUniqueCANIDs(ctx context.Context, in *GetUniqueCANIDsRequest, opts ...grpc.CallOption) (*GetUniqueCANIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniqueCANIDsResponse)
	err := c.cc.Invoke(ctx, CanService_GetUniqueCANIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canServiceClient) GetStatsByCANID(ctx context.Context, in *GetStatsByCANIDRequest, opts ...grpc.CallOption) (*GetStatsByCANIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsByCANIDResponse)
	err := c.cc.Invoke(ctx, CanService_GetStatsByCANID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canServiceClient) GetCANopenMessages(ctx context.Context, in *GetCANopenMessagesRequest, opts ...grpc.CallOption) (*GetCANopenMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCANopenMessagesResponse)
	err := c.cc.Invoke(ctx, CanService_GetCANopenMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canServiceClient) GetCANopenStats(ctx context.Context, in *GetCANopenStatsRequest, opts ...grpc.CallOption) (*GetCANopenStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCANopenStatsResponse)
	err := c.cc.Invoke(ctx, CanService_GetCANopenStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CanServiceServer is the server API for CanService service.
// All implementations must embed UnimplementedCanServiceServer
// for forward compatibility.
type CanServiceServer interface {
	// Get CAN messages with optional filters
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	// Get message count with optional filters
	GetMessageCount(context.Context, *GetMessageCountRequest) (*GetMessageCountResponse, error)
	// Get unique CAN IDs
	GetUniqueCANIDs(context.Context, *GetUniqueCANIDsRequest) (*GetUniqueCANIDsResponse, error)
	// Get statistics grouped by CAN ID
	GetStatsByCANID(context.Context, *GetStatsByCANIDRequest) (*GetStatsByCANIDResponse, error)
	// Get CANopen messages classified by message type
	GetCANopenMessages(context.Context, *GetCANopenMessagesRequest) (*GetCANopenMessagesResponse, error)
	// Get CANopen statistics grouped by message type
	GetCANopenStats(context.Context, *GetCANopenStatsRequest) (*GetCANopenStatsResponse, error)
	mustEmbedUnimplementedCanServiceServer()
}

// UnimplementedCanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCanServiceServer struct{}

func (UnimplementedCanServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedCanServiceServer) GetMessageCount(context.Context, *GetMessageCountRequest) (*GetMessageCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageCount not implemented")
}
func (UnimplementedCanServiceServer) GetUniqueCANIDs(context.Context, *GetUniqueCANIDsRequest) (*GetUniqueCANIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniqueCANIDs not implemented")
}
func (UnimplementedCanServiceServer) GetStatsByCANID(context.Context, *GetStatsByCANIDRequest) (*GetStatsByCANIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatsByCANID not implemented")
}
func (UnimplementedCanServiceServer) GetCANopenMessages(context.Context, *GetCANopenMessagesRequest) (*GetCANopenMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCANopenMessages not implemented")
}
func (UnimplementedCanServiceServer) GetCANopenStats(context.Context, *GetCANopenStatsRequest) (*GetCANopenStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCANopenStats not implemented")
}
func (UnimplementedCanServiceServer) mustEmbedUnimplementedCanServiceServer() {}
func (UnimplementedCanServiceServer) testEmbeddedByValue()                    {}

// UnsafeCanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CanServiceServer will
// result in compilation errors.
type UnsafeCanServiceServer interface {
	mustEmbedUnimplementedCanServiceServer()
}

func RegisterCanServiceServer(s grpc.ServiceRegistrar, srv CanServiceServer) {
	// If the following call panics, it indicates UnimplementedCanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CanService_ServiceDesc, srv)
}

func _CanService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanService_GetMessageCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanServiceServer).GetMessageCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanService_GetMessageCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanServiceServer).GetMessageCount(ctx, req.(*GetMessageCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanService_GetUniqueCANIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniqueCANIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanServiceServer).GetUniqueCANIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanService_GetUniqueCANIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanServiceServer).GetUniqueCANIDs(ctx, req.(*GetUniqueCANIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanService_GetStatsByCANID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByCANIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanServiceServer).GetStatsByCANID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanService_GetStatsByCANID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanServiceServer).GetStatsByCANID(ctx, req.(*GetStatsByCANIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanService_GetCANopenMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCANopenMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanServiceServer).GetCANopenMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanService_GetCANopenMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanServiceServer).GetCANopenMessages(ctx, req.(*GetCANopenMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanService_GetCANopenStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCANopenStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanServiceServer).GetCANopenStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanService_GetCANopenStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanServiceServer).GetCANopenStats(ctx, req.(*GetCANopenStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CanService_ServiceDesc is the grpc.ServiceDesc for CanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.canService",
	HandlerType: (*CanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessages",
			Handler:    _CanService_GetMessages_Handler,
		},
		{
			MethodName: "GetMessageCount",
			Handler:    _CanService_GetMessageCount_Handler,
		},
		{
			MethodName: "GetUniqueCANIDs",
			Handler:    _CanService_GetUniqueCANIDs_Handler,
		},
		{
			MethodName: "GetStatsByCANID",
			Handler:    _CanService_GetStatsByCANID_Handler,
		},
		{
			MethodName: "GetCANopenMessages",
			Handler:    _CanService_GetCANopenMessages_Handler,
		},
		{
			MethodName: "GetCANopenStats",
			Handler:    _CanService_GetCANopenStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/can/can.proto",
}
