// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: api/proto/clickhouse.proto

package clickhouse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClickHouseService_GetMessages_FullMethodName        = "/clickhouse.ClickHouseService/GetMessages"
	ClickHouseService_GetMessageCount_FullMethodName    = "/clickhouse.ClickHouseService/GetMessageCount"
	ClickHouseService_GetUniqueCANIDs_FullMethodName    = "/clickhouse.ClickHouseService/GetUniqueCANIDs"
	ClickHouseService_GetStatsByCANID_FullMethodName    = "/clickhouse.ClickHouseService/GetStatsByCANID"
	ClickHouseService_GetCANopenMessages_FullMethodName = "/clickhouse.ClickHouseService/GetCANopenMessages"
	ClickHouseService_GetCANopenStats_FullMethodName    = "/clickhouse.ClickHouseService/GetCANopenStats"
)

// ClickHouseServiceClient is the client API for ClickHouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClickHouse service definition
type ClickHouseServiceClient interface {
	// Get CAN messages with optional filters
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	// Get message count with optional filters
	GetMessageCount(ctx context.Context, in *GetMessageCountRequest, opts ...grpc.CallOption) (*GetMessageCountResponse, error)
	// Get unique CAN IDs
	GetUniqueCANIDs(ctx context.Context, in *GetUniqueCANIDsRequest, opts ...grpc.CallOption) (*GetUniqueCANIDsResponse, error)
	// Get statistics grouped by CAN ID
	GetStatsByCANID(ctx context.Context, in *GetStatsByCANIDRequest, opts ...grpc.CallOption) (*GetStatsByCANIDResponse, error)
	// Get CANopen messages classified by message type
	GetCANopenMessages(ctx context.Context, in *GetCANopenMessagesRequest, opts ...grpc.CallOption) (*GetCANopenMessagesResponse, error)
	// Get CANopen statistics grouped by message type
	GetCANopenStats(ctx context.Context, in *GetCANopenStatsRequest, opts ...grpc.CallOption) (*GetCANopenStatsResponse, error)
}

type clickHouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClickHouseServiceClient(cc grpc.ClientConnInterface) ClickHouseServiceClient {
	return &clickHouseServiceClient{cc}
}

func (c *clickHouseServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, ClickHouseService_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickHouseServiceClient) GetMessageCount(ctx context.Context, in *GetMessageCountRequest, opts ...grpc.CallOption) (*GetMessageCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageCountResponse)
	err := c.cc.Invoke(ctx, ClickHouseService_GetMessageCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickHouseServiceClient) GetUniqueCANIDs(ctx context.Context, in *GetUniqueCANIDsRequest, opts ...grpc.CallOption) (*GetUniqueCANIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniqueCANIDsResponse)
	err := c.cc.Invoke(ctx, ClickHouseService_GetUniqueCANIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickHouseServiceClient) GetStatsByCANID(ctx context.Context, in *GetStatsByCANIDRequest, opts ...grpc.CallOption) (*GetStatsByCANIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsByCANIDResponse)
	err := c.cc.Invoke(ctx, ClickHouseService_GetStatsByCANID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickHouseServiceClient) GetCANopenMessages(ctx context.Context, in *GetCANopenMessagesRequest, opts ...grpc.CallOption) (*GetCANopenMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCANopenMessagesResponse)
	err := c.cc.Invoke(ctx, ClickHouseService_GetCANopenMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clickHouseServiceClient) GetCANopenStats(ctx context.Context, in *GetCANopenStatsRequest, opts ...grpc.CallOption) (*GetCANopenStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCANopenStatsResponse)
	err := c.cc.Invoke(ctx, ClickHouseService_GetCANopenStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClickHouseServiceServer is the server API for ClickHouseService service.
// All implementations must embed UnimplementedClickHouseServiceServer
// for forward compatibility.
//
// ClickHouse service definition
type ClickHouseServiceServer interface {
	// Get CAN messages with optional filters
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	// Get message count with optional filters
	GetMessageCount(context.Context, *GetMessageCountRequest) (*GetMessageCountResponse, error)
	// Get unique CAN IDs
	GetUniqueCANIDs(context.Context, *GetUniqueCANIDsRequest) (*GetUniqueCANIDsResponse, error)
	// Get statistics grouped by CAN ID
	GetStatsByCANID(context.Context, *GetStatsByCANIDRequest) (*GetStatsByCANIDResponse, error)
	// Get CANopen messages classified by message type
	GetCANopenMessages(context.Context, *GetCANopenMessagesRequest) (*GetCANopenMessagesResponse, error)
	// Get CANopen statistics grouped by message type
	GetCANopenStats(context.Context, *GetCANopenStatsRequest) (*GetCANopenStatsResponse, error)
	mustEmbedUnimplementedClickHouseServiceServer()
}

// UnimplementedClickHouseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClickHouseServiceServer struct{}

func (UnimplementedClickHouseServiceServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedClickHouseServiceServer) GetMessageCount(context.Context, *GetMessageCountRequest) (*GetMessageCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageCount not implemented")
}
func (UnimplementedClickHouseServiceServer) GetUniqueCANIDs(context.Context, *GetUniqueCANIDsRequest) (*GetUniqueCANIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniqueCANIDs not implemented")
}
func (UnimplementedClickHouseServiceServer) GetStatsByCANID(context.Context, *GetStatsByCANIDRequest) (*GetStatsByCANIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatsByCANID not implemented")
}
func (UnimplementedClickHouseServiceServer) GetCANopenMessages(context.Context, *GetCANopenMessagesRequest) (*GetCANopenMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCANopenMessages not implemented")
}
func (UnimplementedClickHouseServiceServer) GetCANopenStats(context.Context, *GetCANopenStatsRequest) (*GetCANopenStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCANopenStats not implemented")
}
func (UnimplementedClickHouseServiceServer) mustEmbedUnimplementedClickHouseServiceServer() {}
func (UnimplementedClickHouseServiceServer) testEmbeddedByValue()                           {}

// UnsafeClickHouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClickHouseServiceServer will
// result in compilation errors.
type UnsafeClickHouseServiceServer interface {
	mustEmbedUnimplementedClickHouseServiceServer()
}

func RegisterClickHouseServiceServer(s grpc.ServiceRegistrar, srv ClickHouseServiceServer) {
	// If the following call panics, it indicates UnimplementedClickHouseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClickHouseService_ServiceDesc, srv)
}

func _ClickHouseService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickHouseServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickHouseService_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickHouseServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickHouseService_GetMessageCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickHouseServiceServer).GetMessageCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickHouseService_GetMessageCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickHouseServiceServer).GetMessageCount(ctx, req.(*GetMessageCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickHouseService_GetUniqueCANIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniqueCANIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickHouseServiceServer).GetUniqueCANIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickHouseService_GetUniqueCANIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickHouseServiceServer).GetUniqueCANIDs(ctx, req.(*GetUniqueCANIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickHouseService_GetStatsByCANID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsByCANIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickHouseServiceServer).GetStatsByCANID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickHouseService_GetStatsByCANID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickHouseServiceServer).GetStatsByCANID(ctx, req.(*GetStatsByCANIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickHouseService_GetCANopenMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCANopenMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickHouseServiceServer).GetCANopenMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickHouseService_GetCANopenMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickHouseServiceServer).GetCANopenMessages(ctx, req.(*GetCANopenMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClickHouseService_GetCANopenStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCANopenStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClickHouseServiceServer).GetCANopenStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClickHouseService_GetCANopenStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClickHouseServiceServer).GetCANopenStats(ctx, req.(*GetCANopenStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClickHouseService_ServiceDesc is the grpc.ServiceDesc for ClickHouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClickHouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clickhouse.ClickHouseService",
	HandlerType: (*ClickHouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessages",
			Handler:    _ClickHouseService_GetMessages_Handler,
		},
		{
			MethodName: "GetMessageCount",
			Handler:    _ClickHouseService_GetMessageCount_Handler,
		},
		{
			MethodName: "GetUniqueCANIDs",
			Handler:    _ClickHouseService_GetUniqueCANIDs_Handler,
		},
		{
			MethodName: "GetStatsByCANID",
			Handler:    _ClickHouseService_GetStatsByCANID_Handler,
		},
		{
			MethodName: "GetCANopenMessages",
			Handler:    _ClickHouseService_GetCANopenMessages_Handler,
		},
		{
			MethodName: "GetCANopenStats",
			Handler:    _ClickHouseService_GetCANopenStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/clickhouse.proto",
}
